# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('category', models.SmallIntegerField(choices=[(0, 'monocasco'), (1, 'bicasco'), (2, 'casco sumergido'), (3, 'planeador'), (4, 'hidrofoil'), (5, 'hovercraft'), (6, 'tricasco'), (7, 'submarino'), (100, 'punto virtual'), (101, 'boya señalizacion'), (102, 'puesto de control'), (103, 'boya de señalización fija')], default=0, verbose_name='categoría del casco')),
                ('acronym', models.CharField(max_length=20, unique=True, verbose_name='acrónimo')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, default='media/uploads/test_images/noimage.png', null=True, upload_to='media/uploads/images/devices/', verbose_name='imagen')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='masa [Kg]')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='eslora [m]')),
                ('sleeve', models.FloatField(blank=True, null=True, verbose_name='manga [m]')),
                ('draft', models.FloatField(blank=True, null=True, verbose_name='calado [m]')),
                ('model3d', models.FileField(blank=True, null=True, upload_to='uploads/models/devices/', verbose_name='modelo 3d')),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha creación')),
                ('is_enable', models.BooleanField(default=True, verbose_name='¿esta operativo?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Organization', verbose_name='fabricante')),
            ],
            options={
                'verbose_name': 'dispositivo',
                'verbose_name_plural': 'dispositivos',
                'db_table': 'dev_node',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_enable', models.DateTimeField(default=django.utils.timezone.now, verbose_name='agregado desde')),
                ('rol', models.SmallIntegerField(choices=[(0, 'dueño'), (1, 'financiero'), (2, 'eléctrico'), (3, 'mecánico'), (4, 'coordinador'), (5, 'programador'), (6, 'diseñador'), (7, 'asesor'), (8, 'técnico')], default=8, verbose_name='rol funcional')),
                ('timestamp_disable', models.DateTimeField(blank=True, null=True, verbose_name='retirado desde')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Contact', verbose_name='perfil contacto')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device', verbose_name='dispositivo')),
            ],
            options={
                'verbose_name': 'trazabilidad del equipo',
                'verbose_name_plural': 'trazabilidad de equipos',
                'db_table': 'team_trace',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='device',
            name='team',
            field=models.ManyToManyField(blank=True, through='devices.TeamTrace', to='profiles.Contact', verbose_name='configuración de equipo'),
        ),
    ]
