# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=50, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=60, verbose_name='apellidos')),
                ('acronym', models.CharField(max_length=20, unique=True, verbose_name='apodo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo-e')),
                ('image', models.ImageField(blank=True, default='media/uploads/test_images/noimage.png', null=True, upload_to='media/uploads/images/profiles/', verbose_name='imagen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='acceso de usuario')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'db_table': 'prf_contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
                ('category', models.SmallIntegerField(choices=[(0, 'emergencias'), (1, 'notificaciones'), (2, 'adquisicion de datos'), (3, 'buscador referencias')], default=2, verbose_name='categoría de monitoreo')),
                ('image', models.ImageField(blank=True, default='media/uploads/test_images/noimage.png', null=True, upload_to='media/uploads/images/profiles/', verbose_name='imagen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='acceso de usuario')),
            ],
            options={
                'verbose_name': 'monitor',
                'verbose_name_plural': 'monitores',
                'db_table': 'prf_monitor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
                ('acronym', models.CharField(max_length=20, unique=True, verbose_name='acrónimo')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='país')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo-e')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='página web')),
                ('image', models.ImageField(blank=True, default='media/uploads/test_images/noimage.png', null=True, upload_to='media/uploads/images/profiles/', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'db_table': 'prf_organization',
                'managed': True,
            },
        ),
    ]
